import { createClient } from 'npm:@supabase/supabase-js@2.112.2';
const cors={ 'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type' };
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')!;const anon=Deno.env.get('SUPABASE_ANON_KEY')!;const serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const auth=req.headers.get('Authorization')??'';const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user}}=await userClient.auth.getUser();if(!user)throw new Error('Sesión inválida.');
 const{documentId}=await req.json() as {documentId:string};const admin=createClient(url,serviceKey);const{data:doc,error:docError}=await admin.from('ef_documentos').select('*').eq('id',documentId).single();if(docError)throw docError;const{data:member}=await userClient.from('rest_miembros').select('rol').eq('empresa_id',doc.empresa_id).eq('user_id',user.id).eq('activo',true).maybeSingle();if(!member)throw new Error('Sin acceso al documento.');
 if(doc.estado==='aceptado')return Response.json({ok:true,duplicatePrevented:true},{headers:cors});
 const{data:cfg}=await admin.from('ef_configuraciones').select('*').eq('empresa_id',doc.empresa_id).single();if(!cfg?.activo)throw new Error('La emisión SUNAT todavía no está activada.');if(!cfg.clave_sol_configurada||!cfg.certificado_configurado)throw new Error('Falta configurar la clave SOL o el certificado digital.');
 const attempt=Number(doc.intentos)+1;await admin.from('ef_documentos').update({estado:'enviando',intentos:attempt,ultimo_intento_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',documentId).neq('estado','aceptado');
 // El ensamblado UBL, firma XMLDSig y SOAP se habilita después de validar el certificado real en pruebas SUNAT.
 const message='Documento reservado sin duplicados. Falta validar el certificado real para activar el envío SOAP a SUNAT.';await admin.from('ef_documentos').update({estado:'error',mensaje_sunat:message,proximo_reintento_at:new Date(Date.now()+300000).toISOString(),updated_at:new Date().toISOString()}).eq('id',documentId);await admin.from('ef_intentos').upsert({empresa_id:doc.empresa_id,documento_id:documentId,numero_intento:attempt,resultado:'error',mensaje:message},{onConflict:'documento_id,numero_intento'});
 return Response.json({ok:false,pendingCertificateValidation:true,message},{status:409,headers:cors});
}catch(e){return Response.json({error:e instanceof Error?e.message:'Error interno'},{status:400,headers:cors});}});
