import { useEffect, useMemo, useState } from 'react';
import { createQuote, getClients, getQuotes, setQuoteStatus, type Client, type Quote, type QuoteItem } from '../services/erp-store';
import { getProducts } from '../services/restaurant-store';
import type { RestaurantProduct } from '../types/restaurant';
const money=new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}),cls='rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold outline-none focus:border-blue-600';
export default function Cotizaciones(){
 const [rows,setRows]=useState<Quote[]>([]),[clients,setClients]=useState<Client[]>([]),[products,setProducts]=useState<RestaurantProduct[]>([]),[items,setItems]=useState<QuoteItem[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [f,setF]=useState({clienteId:'',clienteNombre:'',venceAt:'',observaciones:''});
 const load=async()=>{const [q,c,p]=await Promise.all([getQuotes(),getClients(),getProducts()]);setRows(q);setClients(c.filter(x=>x.activo));setProducts(p)};useEffect(()=>{void Promise.all([getQuotes(),getClients(),getProducts()]).then(([q,c,p])=>{setRows(q);setClients(c.filter(x=>x.activo));setProducts(p)}).catch(e=>setError(e instanceof Error?e.message:'No se pudo cargar.'))},[]);
 const total=useMemo(()=>items.reduce((s,i)=>s+i.cantidad*i.precio,0),[items]);
 const add=(id:string)=>{const p=products.find(x=>x.id===id);if(!p)return;setItems(cur=>{const old=cur.find(x=>x.producto_id===id);return old?cur.map(x=>x.producto_id===id?{...x,cantidad:x.cantidad+1}:x):[...cur,{producto_id:id,descripcion:p.name,cantidad:1,precio:p.price}]})};
 const save=async()=>{if(!f.clienteNombre.trim())return setError('Selecciona o escribe el cliente.');if(!items.length)return setError('Agrega al menos un producto.');setSaving(true);try{await createQuote({clienteId:f.clienteId||undefined,clienteNombre:f.clienteNombre,venceAt:f.venceAt||undefined,observaciones:f.observaciones||undefined,items});setItems([]);setF({clienteId:'',clienteNombre:'',venceAt:'',observaciones:''});await load();setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setSaving(false)}};
 return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-black text-slate-950">Cotizaciones</h1><p className="font-medium text-slate-600">Presupuestos con cliente, productos, vigencia y seguimiento.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}
 <section className="grid gap-5 rounded-2xl border bg-white p-5 lg:grid-cols-2"><div className="space-y-3"><h2 className="text-lg font-black">Nueva cotización</h2><select className={`${cls} w-full`} value={f.clienteId} onChange={e=>{const c=clients.find(x=>x.id===e.target.value);setF({...f,clienteId:e.target.value,clienteNombre:c?.nombre||''})}}><option value="">Cliente nuevo / público</option>{clients.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><input className={`${cls} w-full`} placeholder="Nombre del cliente *" value={f.clienteNombre} onChange={e=>setF({...f,clienteNombre:e.target.value,clienteId:''})}/><input className={`${cls} w-full`} type="date" title="Fecha de vencimiento" value={f.venceAt} onChange={e=>setF({...f,venceAt:e.target.value})}/><select className={`${cls} w-full`} defaultValue="" onChange={e=>{if(e.target.value){add(e.target.value);e.target.value=''}}}><option value="">Agregar producto...</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {money.format(p.price)}</option>)}</select></div><div><h2 className="mb-3 text-lg font-black">Detalle</h2><div className="space-y-2">{items.length===0?<p className="rounded-xl bg-slate-50 p-8 text-center text-slate-500">Agrega productos.</p>:items.map((i,index)=><div key={i.producto_id} className="grid grid-cols-[1fr_80px_100px_32px] items-center gap-2 rounded-xl border p-3"><span className="font-bold">{i.descripcion}</span><input className="w-full rounded-lg border p-2" inputMode="decimal" value={i.cantidad} onChange={e=>setItems(items.map((x,n)=>n===index?{...x,cantidad:Number(e.target.value)}:x))}/><span className="font-black">{money.format(i.cantidad*i.precio)}</span><button onClick={()=>setItems(items.filter((_,n)=>n!==index))} className="font-black text-red-600">×</button></div>)}</div><div className="mt-4 flex items-center justify-between text-xl font-black"><span>Total</span><span>{money.format(total)}</span></div><button disabled={saving} onClick={()=>void save()} className="mt-4 w-full rounded-xl bg-blue-600 py-3 font-black text-white disabled:opacity-50">{saving?'Guardando...':'Guardar cotización'}</button></div></section>
 <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-600"><tr><th className="p-4">Número</th><th>Cliente</th><th>Fecha</th><th>Total</th><th>Estado</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={5} className="p-10 text-center text-slate-500">Aún no hay cotizaciones.</td></tr>:rows.map(r=><tr key={r.id}><td className="p-4 font-black">COT-{String(r.numero).padStart(6,'0')}</td><td>{r.cliente_nombre}</td><td>{new Date(r.created_at).toLocaleDateString('es-PE')}</td><td className="font-black">{money.format(r.total)}</td><td><select className="rounded-lg border p-2 font-bold" value={r.estado} onChange={async e=>{await setQuoteStatus(r.id,e.target.value as Quote['estado']);await load()}}><option>borrador</option><option>enviada</option><option>aceptada</option><option>rechazada</option><option>vencida</option></select></td></tr>)}</tbody></table></section></div>
}
