import { useEffect, useState } from 'react';
import { getOrders, orderTotal } from '../services/restaurant-store';
import type { RestaurantOrder } from '../types/restaurant';
const money=new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'});
const safe=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]??c));
function printReceipt(order:RestaurantOrder){
 const popup=window.open('','_blank','width=420,height=700');if(!popup)return alert('Permite las ventanas emergentes para imprimir el comprobante.');
 const items=order.items.map(i=>`<tr><td>${i.quantity} × ${safe(i.name)}</td><td style="text-align:right">${money.format(i.quantity*i.unitPrice)}</td></tr>`).join('');
 popup.document.title=`Ticket-${order.number}`;
 popup.document.body.innerHTML=`<main><h1>CHICKEN HUERTA</h1><p>COMPROBANTE INTERNO DE VENTA</p><hr><div>Ticket: <b>T-${String(order.number).padStart(8,'0')}</b></div><div>Fecha: ${new Date(order.updatedAt).toLocaleString('es-PE')}</div><div>Cliente: ${safe(order.customer||'Público general')}</div><div>Servicio: ${safe(order.serviceType)} ${order.table?`· ${safe(order.table)}`:''}</div><hr><table>${items}</table><hr><div class="total"><span>TOTAL</span><span>${money.format(orderTotal(order))}</span></div><div>Método: ${safe(order.paymentMethod||'No indicado')}</div><hr><p>Documento de prueba sin validez tributaria SUNAT</p><p>¡Gracias por su compra!</p></main><style>@page{size:80mm auto;margin:4mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#000}main{width:72mm;margin:auto;font-size:12px}h1{text-align:center;font-size:20px;margin:0}p{text-align:center;margin:5px 0}hr{border:0;border-top:1px dashed #000;margin:10px 0}table{width:100%;border-collapse:collapse}td{padding:4px 0;vertical-align:top}.total{display:flex;justify-content:space-between;font-size:17px;font-weight:800;margin:8px 0}</style>`;
 popup.focus();setTimeout(()=>{popup.print();popup.close()},250);
}
export default function Facturacion(){const [rows,setRows]=useState<RestaurantOrder[]>([]),[error,setError]=useState('');useEffect(()=>{void getOrders().then(data=>setRows(data.filter(r=>r.status==='pagado'))).catch(e=>setError(e instanceof Error?e.message:'No se pudo cargar.'))},[]);return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-black text-slate-950">Comprobantes de venta</h1><p className="font-medium text-slate-600">Registro interno de ventas cobradas. La emisión oficial SUNAT se habilitará con certificado y proveedor electrónico.</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 font-bold text-amber-800">Modo de prueba: estos comprobantes son internos y no tienen validez tributaria SUNAT.</div>{error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}<section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-600"><tr><th className="p-4">Documento interno</th><th>Fecha</th><th>Cliente</th><th>Método</th><th>Total</th><th>Acción</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={6} className="p-12 text-center text-slate-500">Todavía no hay ventas cobradas.</td></tr>:rows.map(r=><tr key={r.id}><td className="p-4 font-black">T-{String(r.number).padStart(8,'0')}</td><td>{new Date(r.updatedAt).toLocaleString('es-PE')}</td><td>{r.customer||'Público general'}</td><td>{r.paymentMethod||'—'}</td><td className="font-black">{money.format(orderTotal(r))}</td><td><button onClick={()=>printReceipt(r)} className="font-black text-blue-600">Imprimir ticket</button></td></tr>)}</tbody></table></section></div>}
