import { useEffect, useMemo, useState, type ReactElement, type ReactNode } from 'react';
import { AlertTriangle, ArrowDownUp, BookOpen, Package, Plus, Trash2 } from 'lucide-react';
import { getProducts } from '../services/restaurant-store';
import { deleteRecipeLine, getInventoryMovements, getRecipeLines, getSupplies, registerInventoryMovement, saveRecipeLine, saveSupply, type InventoryMovement, type RecipeLine, type Supply } from '../services/inventory-store';
import type { RestaurantProduct } from '../types/restaurant';

const emptySupply={code:'',name:'',category:'Cárnicos',unit:'unidad',stock:0,minStock:0};
function message(reason:unknown,fallback:string){return reason instanceof Error?reason.message:fallback;}
export default function Inventario(){
 const [tab,setTab]=useState<'insumos'|'kardex'|'recetas'>('insumos'); const [supplies,setSupplies]=useState<Supply[]>([]); const [movements,setMovements]=useState<InventoryMovement[]>([]); const [recipes,setRecipes]=useState<RecipeLine[]>([]); const [products,setProducts]=useState<RestaurantProduct[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const [supply,setSupply]=useState(emptySupply); const [movement,setMovement]=useState({supplyId:'',type:'entrada',quantity:0,reason:''}); const [recipe,setRecipe]=useState({productId:'',supplyId:'',quantity:0});
 const load=async()=>{try{setError('');const [a,b,c,d]=await Promise.all([getSupplies(),getInventoryMovements(),getRecipeLines(),getProducts()]);setSupplies(a);setMovements(b);setRecipes(c);setProducts(d);}catch(e:unknown){setError(message(e,'No se pudo cargar inventario.'));}};
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[]); const low=useMemo(()=>supplies.filter(x=>x.stock<=x.minStock),[supplies]);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();await load();}catch(e:unknown){setError(message(e,'No se pudo guardar.'));}finally{setBusy(false);}};
 return <div className="min-h-screen bg-slate-50 p-4 lg:p-6">
  {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
  <div className="mb-6"><h1 className="text-3xl font-black text-slate-900">Inventario y recetas</h1><p className="text-sm text-slate-500">Stock real, kardex y consumo automático por venta</p></div>
  <div className="mb-6 grid gap-4 sm:grid-cols-3"><Card icon={<Package/>} label="Insumos activos" value={supplies.length}/><Card icon={<AlertTriangle/>} label="Stock bajo" value={low.length}/><Card icon={<BookOpen/>} label="Líneas de receta" value={recipes.length}/></div>
  <div className="mb-5 flex gap-2 overflow-x-auto">{([['insumos','Insumos'],['kardex','Kardex'],['recetas','Recetas']] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-5 py-2.5 text-sm font-bold ${tab===id?'bg-blue-600 text-white':'bg-white text-slate-600'}`}>{label}</button>)}</div>
  {tab==='insumos'&&<div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Panel title="Nuevo insumo"><Field label="Código"><input value={supply.code} onChange={e=>setSupply({...supply,code:e.target.value})}/></Field><Field label="Nombre"><input value={supply.name} onChange={e=>setSupply({...supply,name:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Categoría"><input value={supply.category} onChange={e=>setSupply({...supply,category:e.target.value})}/></Field><Field label="Unidad"><select value={supply.unit} onChange={e=>setSupply({...supply,unit:e.target.value})}>{['unidad','kg','g','litro','ml'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Stock inicial"><input type="number" step="0.001" value={supply.stock} onChange={e=>setSupply({...supply,stock:Number(e.target.value)})}/></Field><Field label="Stock mínimo"><input type="number" step="0.001" value={supply.minStock} onChange={e=>setSupply({...supply,minStock:Number(e.target.value)})}/></Field></div><button disabled={busy||!supply.code||!supply.name} onClick={()=>void run(async()=>{await saveSupply(supply);setSupply(emptySupply);})} className="mt-4 w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-50"><Plus className="mr-2 inline h-4 w-4"/>Guardar insumo</button></Panel><Panel title="Existencias"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-400"><th className="p-3">Código / insumo</th><th>Stock</th><th>Mínimo</th><th>Estado</th></tr></thead><tbody>{supplies.map(x=><tr key={x.id} className="border-b"><td className="p-3"><b>{x.name}</b><small className="block text-slate-400">{x.code} · {x.category}</small></td><td className="font-bold">{x.stock} {x.unit}</td><td>{x.minStock} {x.unit}</td><td><span className={`rounded-full px-2 py-1 text-xs font-bold ${x.stock<=x.minStock?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{x.stock<=x.minStock?'Reponer':'Correcto'}</span></td></tr>)}</tbody></table>{!supplies.length&&<Empty text="Aún no hay insumos. Registra el primero."/>}</div></Panel></div>}
  {tab==='kardex'&&<div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Panel title="Registrar movimiento"><Field label="Insumo"><select value={movement.supplyId} onChange={e=>setMovement({...movement,supplyId:e.target.value})}><option value="">Seleccionar</option>{supplies.map(x=><option key={x.id} value={x.id}>{x.name} · {x.stock} {x.unit}</option>)}</select></Field><Field label="Tipo"><select value={movement.type} onChange={e=>setMovement({...movement,type:e.target.value})}><option value="entrada">Entrada</option><option value="salida">Salida</option><option value="merma">Merma</option><option value="ajuste">Ajuste (+ o -)</option></select></Field><Field label="Cantidad"><input type="number" step="0.001" value={movement.quantity} onChange={e=>setMovement({...movement,quantity:Number(e.target.value)})}/></Field><Field label="Motivo"><input value={movement.reason} onChange={e=>setMovement({...movement,reason:e.target.value})} placeholder="Compra, pérdida, conteo..."/></Field><button disabled={busy||!movement.supplyId||!movement.quantity} onClick={()=>void run(async()=>{await registerInventoryMovement(movement.supplyId,movement.type,movement.quantity,movement.reason);setMovement({...movement,quantity:0,reason:''});})} className="mt-4 w-full rounded-xl bg-slate-900 py-3 font-bold text-white disabled:opacity-50"><ArrowDownUp className="mr-2 inline h-4 w-4"/>Registrar</button></Panel><Panel title="Movimientos recientes"><div className="space-y-2">{movements.map(x=><div key={x.id} className="flex flex-col justify-between gap-2 rounded-xl border p-3 sm:flex-row"><div><b>{x.supplyName}</b><p className="text-xs text-slate-500">{x.reason} · {x.responsible}</p></div><div className="text-right"><b className={['entrada'].includes(x.type)?'text-emerald-600':'text-red-600'}>{x.type==='entrada'?'+':'-'}{x.quantity}</b><p className="text-xs text-slate-400">{x.previous} → {x.current}</p></div></div>)}{!movements.length&&<Empty text="Aún no hay movimientos."/>}</div></Panel></div>}
  {tab==='recetas'&&<div className="grid gap-5 xl:grid-cols-[400px_1fr]"><Panel title="Agregar ingrediente a receta"><Field label="Producto de venta"><select value={recipe.productId} onChange={e=>setRecipe({...recipe,productId:e.target.value})}><option value="">Seleccionar plato</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Insumo"><select value={recipe.supplyId} onChange={e=>setRecipe({...recipe,supplyId:e.target.value})}><option value="">Seleccionar insumo</option>{supplies.map(x=><option key={x.id} value={x.id}>{x.name} ({x.unit})</option>)}</select></Field><Field label="Cantidad utilizada por una venta"><input type="number" min="0.001" step="0.001" value={recipe.quantity} onChange={e=>setRecipe({...recipe,quantity:Number(e.target.value)})}/></Field><p className="mt-2 text-xs text-blue-600">Ejemplo: 1 pollo entero usa 1 unidad de pollo crudo. Cada venta descontará esta receta automáticamente.</p><button disabled={busy||!recipe.productId||!recipe.supplyId||recipe.quantity<=0} onClick={()=>void run(()=>saveRecipeLine(recipe.productId,recipe.supplyId,recipe.quantity))} className="mt-4 w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-50">Guardar ingrediente</button></Panel><Panel title="Recetas configuradas"><div className="space-y-2">{recipes.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-3"><div><b>{x.productName}</b><p className="text-sm text-slate-500">{x.quantity} {x.unit} de {x.supplyName}</p></div><button onClick={()=>void run(()=>deleteRecipeLine(x.id))} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div>)}{!recipes.length&&<Empty text="Todavía no hay recetas. Agrega los ingredientes reales de cada plato."/>}</div></Panel></div>}
 </div>;
}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-black text-slate-900">{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:ReactElement}){return <label className="mb-3 block text-xs font-bold uppercase text-slate-500">{label}{<span className="mt-1 block [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-slate-200 [&>*]:p-3 [&>*]:font-normal [&>*]:normal-case [&>*]:text-slate-900">{children}</span>}</label>}
function Card({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <div className="rounded-2xl border bg-white p-5"><div className="mb-2 flex items-center gap-2 text-sm font-semibold text-slate-500">{icon}{label}</div><b className="text-3xl">{value}</b></div>}
function Empty({text}:{text:string}){return <p className="p-8 text-center text-sm text-slate-400">{text}</p>}
