import { useCallback, useEffect, useMemo, useState } from 'react';
import { cancelOrder, getOrders, orderTotal, subscribeRestaurantData } from '../services/restaurant-store';
import type { RestaurantOrder } from '../types/restaurant';
import { useNotification } from '../context/notification-context';
import { userErrorMessage } from '../lib/errors';
const money=new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'});
export default function Pedidos(){
 const [rows,setRows]=useState<RestaurantOrder[]>([]),[filter,setFilter]=useState('todos'),[error,setError]=useState(''),[live,setLive]=useState(false);const {notify}=useNotification();
 const load=useCallback(()=>getOrders().then(data=>{setRows(data);setError('')}).catch((reason:unknown)=>{const message=userErrorMessage(reason,'No se pudieron cargar los pedidos.');setError(message);notify(message,'error')}),[notify]);
 useEffect(()=>{let active=true;let unsubscribe:(()=>void)|undefined;const refresh=()=>{if(active)void load()};refresh();void subscribeRestaurantData(refresh,status=>{if(!active)return;setLive(status==='connected');if(status==='error')notify('Se perdió la actualización en tiempo real. Intentando reconectar…','error')}).then(cleanup=>{unsubscribe=cleanup}).catch((reason:unknown)=>{const message=userErrorMessage(reason,'No se pudo iniciar la actualización en tiempo real.');setError(message);notify(message,'error')});return()=>{active=false;unsubscribe?.()}},[load,notify]);
 const visible=useMemo(()=>filter==='todos'?rows:rows.filter(row=>row.status===filter),[rows,filter]);
 const annul=async(row:RestaurantOrder)=>{const reason=prompt(`Motivo obligatorio para anular el pedido #${row.number}:`);if(!reason?.trim())return;try{await cancelOrder(row.id,reason);notify('Pedido anulado y stock restaurado cuando correspondía.','success');await load()}catch(e){const message=userErrorMessage(e,'No se pudo anular el pedido.');setError(message);notify(message,'error')}};
 return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-black text-slate-950">Pedidos</h1><p className="font-medium text-slate-600">Seguimiento real desde la comanda hasta el cobro.</p><span className={`text-xs font-bold ${live?'text-emerald-600':'text-amber-600'}`}>{live?'● En tiempo real':'● Conectando…'}</span></div>{error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}<div className="flex flex-wrap gap-2">{['todos','nuevo','preparando','listo','entregado','pagado','anulado'].map(status=><button key={status} onClick={()=>setFilter(status)} className={`rounded-full px-4 py-2 text-sm font-black capitalize ${filter===status?'bg-blue-600 text-white':'bg-white text-slate-600'}`}>{status}</button>)}</div><section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-600"><tr><th className="p-4">Pedido</th><th>Servicio</th><th>Detalle</th><th>Estado</th><th>Pago</th><th>Total</th><th>Acción</th></tr></thead><tbody className="divide-y">{visible.length===0?<tr><td colSpan={7} className="p-12 text-center text-slate-500">No hay pedidos en este estado.</td></tr>:visible.map(row=><tr key={row.id}><td className="p-4 font-black">#{String(row.number).padStart(3,'0')}<small className="block font-medium text-slate-500">{new Date(row.createdAt).toLocaleString('es-PE')}</small></td><td className="capitalize">{row.serviceType}<small className="block text-slate-500">{row.table||row.customer||'—'}</small></td><td>{row.items.reduce((total,item)=>total+item.quantity,0)} productos</td><td><span className={`rounded-full px-3 py-1 text-xs font-black ${row.status==='anulado'?'bg-red-100 text-red-700':'bg-blue-50 text-blue-700'}`}>{row.status}</span></td><td>{row.paymentMethod||'Pendiente'}</td><td className="font-black">{money.format(orderTotal(row))}</td><td>{row.status!=='anulado'&&<button onClick={()=>void annul(row)} className="font-black text-red-600">Anular</button>}</td></tr>)}</tbody></table></section></div>;
}
