import { useEffect, useState } from 'react';
import { archiveRecord, createSupplier, getSuppliers, type Supplier } from '../services/erp-store';

const cls='rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-blue-600';
export default function Proveedores(){
 const [rows,setRows]=useState<Supplier[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [f,setF]=useState({ruc:'',razon_social:'',contacto:'',telefono:'',email:'',direccion:'',condicion_pago:'Contado'});
 const load=async()=>{try{setRows(await getSuppliers());setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.')}};
 useEffect(()=>{void getSuppliers().then(setRows).catch(e=>setError(e instanceof Error?e.message:'No se pudo cargar.'))},[]);
 const save=async()=>{if(!f.razon_social.trim())return setError('Ingresa el nombre del proveedor.');setSaving(true);try{await createSupplier({...f,ruc:f.ruc||null,contacto:f.contacto||null,telefono:f.telefono||null,email:f.email||null,direccion:f.direccion||null});setF({ruc:'',razon_social:'',contacto:'',telefono:'',email:'',direccion:'',condicion_pago:'Contado'});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setSaving(false)}};
 return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-black text-slate-950">Proveedores</h1><p className="font-medium text-slate-600">Directorio para compras, deuda y abastecimiento.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}
 <section className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-4"><input className={cls} placeholder="RUC" value={f.ruc} onChange={e=>setF({...f,ruc:e.target.value})}/><input className={`${cls} md:col-span-2`} placeholder="Razón social o proveedor *" value={f.razon_social} onChange={e=>setF({...f,razon_social:e.target.value})}/><input className={cls} placeholder="Persona de contacto" value={f.contacto} onChange={e=>setF({...f,contacto:e.target.value})}/><input className={cls} placeholder="Teléfono" value={f.telefono} onChange={e=>setF({...f,telefono:e.target.value})}/><input className={cls} placeholder="Correo" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><select className={cls} value={f.condicion_pago} onChange={e=>setF({...f,condicion_pago:e.target.value})}><option>Contado</option><option>Crédito 7 días</option><option>Crédito 15 días</option><option>Crédito 30 días</option></select><button disabled={saving} onClick={()=>void save()} className="rounded-xl bg-blue-600 px-5 py-3 font-black text-white disabled:opacity-50">{saving?'Guardando...':'Guardar proveedor'}</button></section>
 <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-600"><tr><th className="p-4">Proveedor</th><th>RUC</th><th>Contacto</th><th>Condición</th><th>Acción</th></tr></thead><tbody className="divide-y">{rows.filter(r=>r.activo).length===0?<tr><td colSpan={5} className="p-10 text-center text-slate-500">Aún no hay proveedores.</td></tr>:rows.filter(r=>r.activo).map(r=><tr key={r.id}><td className="p-4 font-bold">{r.razon_social}</td><td>{r.ruc||'—'}</td><td>{r.contacto||r.telefono||'—'}</td><td>{r.condicion_pago}</td><td><button className="font-bold text-red-600" onClick={async()=>{if(confirm('¿Archivar proveedor?')){await archiveRecord('erp_proveedores',r.id);await load()}}}>Archivar</button></td></tr>)}</tbody></table></section></div>
}
