import { useEffect, useState } from 'react';
import { createEmployee, getEmployees, setEmployeeStatus, type Employee } from '../services/erp-store';
const cls='rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold outline-none focus:border-blue-600';
export default function RecursosHumanos(){
 const [rows,setRows]=useState<Employee[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [f,setF]=useState({dni:'',nombres:'',apellidos:'',cargo:'Cajero',area:'Operaciones',telefono:'',email:'',fecha_ingreso:new Date().toISOString().slice(0,10),sueldo:''});
 const load=async()=>{try{setRows(await getEmployees());setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar personal.')}};useEffect(()=>{void getEmployees().then(setRows).catch(e=>setError(e instanceof Error?e.message:'No se pudo cargar personal.'))},[]);
 const save=async()=>{if(!f.nombres||!f.apellidos)return setError('Completa nombres y apellidos.');setSaving(true);try{await createEmployee({...f,dni:f.dni||null,telefono:f.telefono||null,email:f.email||null,sueldo:Number(f.sueldo||0)});setF({...f,dni:'',nombres:'',apellidos:'',telefono:'',email:'',sueldo:''});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setSaving(false)}};
 return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-black text-slate-950">Recursos Humanos</h1><p className="font-medium text-slate-600">Personal, cargo, área, ingreso y remuneración.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}
 <section className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-4"><input className={cls} placeholder="DNI" value={f.dni} onChange={e=>setF({...f,dni:e.target.value})}/><input className={cls} placeholder="Nombres *" value={f.nombres} onChange={e=>setF({...f,nombres:e.target.value})}/><input className={cls} placeholder="Apellidos *" value={f.apellidos} onChange={e=>setF({...f,apellidos:e.target.value})}/><select className={cls} value={f.cargo} onChange={e=>setF({...f,cargo:e.target.value})}><option>Cajero</option><option>Mozo</option><option>Moza + Cajera</option><option>Cocinero</option><option>Supervisor</option><option>Administrador</option><option>Repartidor</option><option>Almacenero</option></select><select className={cls} value={f.area} onChange={e=>setF({...f,area:e.target.value})}><option>Operaciones</option><option>Cocina</option><option>Administración</option><option>Almacén</option><option>Delivery</option></select><input className={cls} type="date" value={f.fecha_ingreso} onChange={e=>setF({...f,fecha_ingreso:e.target.value})}/><div className="flex items-center rounded-xl border border-slate-300 px-4 font-bold">S/&nbsp;<input className="w-full py-3 outline-none" inputMode="decimal" placeholder="Sueldo" value={f.sueldo} onChange={e=>setF({...f,sueldo:e.target.value.replace(/[^0-9.]/g,'')})}/></div><button disabled={saving} onClick={()=>void save()} className="rounded-xl bg-blue-600 font-black text-white disabled:opacity-50">{saving?'Guardando...':'Registrar personal'}</button></section>
 <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-600"><tr><th className="p-4">Personal</th><th>Cargo</th><th>Ingreso</th><th>Sueldo</th><th>Estado</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={5} className="p-10 text-center text-slate-500">Aún no hay personal registrado.</td></tr>:rows.map(r=><tr key={r.id}><td className="p-4 font-bold">{r.nombres} {r.apellidos}<small className="block font-medium text-slate-500">DNI {r.dni||'—'}</small></td><td>{r.cargo}<small className="block text-slate-500">{r.area}</small></td><td>{r.fecha_ingreso}</td><td>S/ {Number(r.sueldo).toFixed(2)}</td><td><button onClick={async()=>{await setEmployeeStatus(r.id,r.estado==='activo'?'inactivo':'activo');await load()}} className={`rounded-full px-3 py-1 font-bold ${r.estado==='activo'?'bg-emerald-100 text-emerald-700':'bg-slate-200'}`}>{r.estado}</button></td></tr>)}</tbody></table></section></div>;
}
