import { useEffect, useMemo, useState } from 'react';
import { createEmployee, getEmployees, getPayrollPayments, registerPayrollPayment, setEmployeeStatus, type Employee, type PayrollPayment } from '../services/erp-store';
const cls='rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold outline-none focus:border-blue-600';
const todayPeriod=()=>new Intl.DateTimeFormat('es-PE',{month:'long',year:'numeric',timeZone:'America/Lima'}).format(new Date());
export default function RecursosHumanos(){
 const [rows,setRows]=useState<Employee[]>([]),[payments,setPayments]=useState<PayrollPayment[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const [f,setF]=useState({dni:'',nombres:'',apellidos:'',cargo:'Cajero',area:'Operaciones',telefono:'',email:'',fecha_ingreso:new Date().toISOString().slice(0,10),sueldo:''});
 const [pay,setPay]=useState({employeeId:'',period:todayPeriod(),amount:'',paymentMethod:'Efectivo',note:''});
 const load=async()=>{try{const [employees,paymentRows]=await Promise.all([getEmployees(),getPayrollPayments()]);setRows(employees);setPayments(paymentRows);setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar personal.')}};
 useEffect(()=>{void Promise.all([getEmployees(),getPayrollPayments()]).then(([employees,paymentRows])=>{setRows(employees);setPayments(paymentRows)}).catch(e=>setError(e instanceof Error?e.message:'No se pudo cargar personal.'))},[]);
 const save=async()=>{if(!f.nombres||!f.apellidos)return setError('Completa nombres y apellidos.');setSaving(true);try{await createEmployee({...f,dni:f.dni||null,telefono:f.telefono||null,email:f.email||null,sueldo:Number(f.sueldo||0)});setF({...f,dni:'',nombres:'',apellidos:'',telefono:'',email:'',sueldo:''});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setSaving(false)}};
 const selected=useMemo(()=>rows.find(row=>row.id===pay.employeeId),[rows,pay.employeeId]);
 const payWorker=async()=>{if(!pay.employeeId||!pay.period.trim()||Number(pay.amount)<=0)return setError('Selecciona trabajador, periodo y monto.');setSaving(true);try{await registerPayrollPayment({employeeId:pay.employeeId,period:pay.period,amount:Number(pay.amount),paymentMethod:pay.paymentMethod,note:pay.note});setNotice('Pago registrado como egreso en contabilidad'+(pay.paymentMethod==='Efectivo'?' y descontado de caja.':'.'));setPay({...pay,amount:'',note:''});await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo registrar el pago.')}finally{setSaving(false)}};
 return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-black text-slate-950">Recursos Humanos</h1><p className="font-medium text-slate-600">Personal, remuneraciones y pagos con efecto real en gastos y caja.</p></div>{error&&<div className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</div>}{notice&&<div className="rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">{notice}</div>}
 <section className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-4"><input className={cls} placeholder="DNI" value={f.dni} onChange={e=>setF({...f,dni:e.target.value})}/><input className={cls} placeholder="Nombres *" value={f.nombres} onChange={e=>setF({...f,nombres:e.target.value})}/><input className={cls} placeholder="Apellidos *" value={f.apellidos} onChange={e=>setF({...f,apellidos:e.target.value})}/><select className={cls} value={f.cargo} onChange={e=>setF({...f,cargo:e.target.value})}><option>Cajero</option><option>Mozo</option><option>Moza + Cajera</option><option>Cocinero</option><option>Supervisor</option><option>Administrador</option><option>Repartidor</option><option>Almacenero</option></select><select className={cls} value={f.area} onChange={e=>setF({...f,area:e.target.value})}><option>Operaciones</option><option>Cocina</option><option>Administración</option><option>Almacén</option><option>Delivery</option></select><input className={cls} type="date" value={f.fecha_ingreso} onChange={e=>setF({...f,fecha_ingreso:e.target.value})}/><div className="flex items-center rounded-xl border border-slate-300 px-4 font-bold">S/&nbsp;<input className="w-full py-3 outline-none" inputMode="decimal" placeholder="Sueldo" value={f.sueldo} onChange={e=>setF({...f,sueldo:e.target.value.replace(/[^0-9.]/g,'')})}/></div><button disabled={saving} onClick={()=>void save()} className="rounded-xl bg-blue-600 font-black text-white disabled:opacity-50">{saving?'Guardando...':'Registrar personal'}</button></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">Registrar pago a trabajador</h2><p className="mb-4 text-sm text-slate-500">El pago se mostrará en gastos. Si es efectivo, también reduce el dinero esperado de la caja abierta.</p><div className="grid gap-3 md:grid-cols-5"><select className={cls} value={pay.employeeId} onChange={e=>{const worker=rows.find(row=>row.id===e.target.value);setPay({...pay,employeeId:e.target.value,amount:worker?String(worker.sueldo):''})}}><option value="">Seleccionar trabajador</option>{rows.filter(row=>row.estado==='activo').map(row=><option key={row.id} value={row.id}>{row.nombres} {row.apellidos}</option>)}</select><input className={cls} placeholder="Periodo" value={pay.period} onChange={e=>setPay({...pay,period:e.target.value})}/><input className={cls} inputMode="decimal" placeholder="Monto S/" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value.replace(/[^0-9.]/g,'')})}/><select className={cls} value={pay.paymentMethod} onChange={e=>setPay({...pay,paymentMethod:e.target.value})}><option>Efectivo</option><option>Yape/Plin</option><option>Transferencia</option><option>Tarjeta</option></select><button disabled={saving} onClick={()=>void payWorker()} className="rounded-xl bg-emerald-600 font-black text-white disabled:opacity-50">Registrar pago</button></div><input className={`${cls} mt-3 w-full`} placeholder="Observación opcional: adelanto, quincena, sueldo completo..." value={pay.note} onChange={e=>setPay({...pay,note:e.target.value})}/>{selected&&<p className="mt-2 text-xs font-bold text-slate-500">Sueldo registrado: S/ {Number(selected.sueldo).toFixed(2)}</p>}</section>
 <section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-600"><tr><th className="p-4">Personal</th><th>Cargo</th><th>Ingreso</th><th>Sueldo</th><th>Estado</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={5} className="p-10 text-center text-slate-500">Aún no hay personal registrado.</td></tr>:rows.map(r=><tr key={r.id}><td className="p-4 font-bold">{r.nombres} {r.apellidos}<small className="block font-medium text-slate-500">DNI {r.dni||'—'}</small></td><td>{r.cargo}<small className="block text-slate-500">{r.area}</small></td><td>{r.fecha_ingreso}</td><td>S/ {Number(r.sueldo).toFixed(2)}</td><td><button onClick={async()=>{if(!confirm(`¿${r.estado==='activo'?'Desactivar':'Reactivar'} a este trabajador?`))return;await setEmployeeStatus(r.id,r.estado==='activo'?'inactivo':'activo');await load()}} className={`rounded-full px-3 py-1 font-bold ${r.estado==='activo'?'bg-emerald-100 text-emerald-700':'bg-slate-200'}`}>{r.estado}</button></td></tr>)}</tbody></table></section>
 <section className="overflow-x-auto rounded-2xl border bg-white"><h2 className="p-5 text-lg font-black">Últimos pagos</h2><table className="w-full min-w-[700px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Fecha</th><th>Trabajador</th><th>Periodo</th><th>Método</th><th>Monto</th></tr></thead><tbody className="divide-y">{payments.map(payment=>{const employee=rows.find(row=>row.id===payment.empleado_id);return <tr key={payment.id}><td className="p-4">{new Date(payment.created_at).toLocaleString('es-PE')}</td><td className="font-bold">{employee?`${employee.nombres} ${employee.apellidos}`:'Trabajador'}</td><td>{payment.periodo}</td><td>{payment.metodo_pago}</td><td className="font-black text-red-600">-S/ {payment.monto.toFixed(2)}</td></tr>})}</tbody></table>{payments.length===0&&<p className="p-8 text-center text-slate-400">Aún no hay pagos registrados.</p>}</section></div>;
}
