-- Base funcional para la versión integral de prueba (sin IA, proyectos ni servicios).
create table if not exists public.erp_clientes (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 tipo_documento text not null default 'DNI', numero_documento text, nombre text not null, telefono text, email text,
 direccion text, activo boolean not null default true, created_at timestamptz not null default now(), unique(empresa_id,numero_documento)
);
create table if not exists public.erp_proveedores (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 ruc text, razon_social text not null, contacto text, telefono text, email text, direccion text,
 condicion_pago text not null default 'Contado', activo boolean not null default true, created_at timestamptz not null default now(), unique(empresa_id,ruc)
);
create table if not exists public.erp_cotizaciones (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 sucursal_id uuid not null references public.rest_sucursales(id) on delete restrict, numero bigint generated by default as identity,
 cliente_id uuid references public.erp_clientes(id) on delete set null, cliente_nombre text not null, estado text not null default 'borrador' check(estado in('borrador','enviada','aceptada','rechazada','vencida')),
 total numeric(12,2) not null default 0, vence_at date, observaciones text, creado_por uuid references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.erp_cotizacion_items (
 id uuid primary key default gen_random_uuid(), cotizacion_id uuid not null references public.erp_cotizaciones(id) on delete cascade,
 producto_id uuid references public.rest_productos(id) on delete set null, descripcion text not null, cantidad numeric(12,3) not null check(cantidad>0), precio numeric(12,2) not null check(precio>=0)
);
create table if not exists public.erp_empleados (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 dni text, nombres text not null, apellidos text not null, cargo text not null, area text not null, telefono text, email text,
 fecha_ingreso date not null default current_date, sueldo numeric(12,2) not null default 0, estado text not null default 'activo' check(estado in('activo','inactivo')), created_at timestamptz not null default now(), unique(empresa_id,dni)
);
create table if not exists public.erp_documentos (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 nombre text not null, categoria text not null default 'Otros', descripcion text, url text, vence_at date,
 creado_por uuid references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.erp_tareas (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 titulo text not null, descripcion text, fecha date not null, hora time, prioridad text not null default 'media' check(prioridad in('baja','media','alta')),
 estado text not null default 'pendiente' check(estado in('pendiente','completada')), responsable text, created_at timestamptz not null default now()
);
create table if not exists public.erp_movimientos_contables (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 fecha date not null default current_date, tipo text not null check(tipo in('ingreso','egreso')), categoria text not null,
 descripcion text not null, monto numeric(12,2) not null check(monto>0), metodo_pago text, referencia text,
 registrado_por uuid references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.erp_configuracion (
 empresa_id uuid primary key references public.rest_empresas(id) on delete cascade, moneda text not null default 'PEN', igv numeric(5,2) not null default 18,
 serie_boleta text not null default 'B001', serie_factura text not null default 'F001', logo_url text, updated_at timestamptz not null default now()
);

do $$ declare t text; begin
 foreach t in array array['erp_clientes','erp_proveedores','erp_cotizaciones','erp_empleados','erp_documentos','erp_tareas','erp_movimientos_contables','erp_configuracion'] loop execute format('alter table public.%I enable row level security',t); end loop;
end $$;
drop policy if exists erp_clientes_miembros on public.erp_clientes; create policy erp_clientes_miembros on public.erp_clientes for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
drop policy if exists erp_proveedores_miembros on public.erp_proveedores; create policy erp_proveedores_miembros on public.erp_proveedores for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
drop policy if exists erp_cotizaciones_miembros on public.erp_cotizaciones; create policy erp_cotizaciones_miembros on public.erp_cotizaciones for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
alter table public.erp_cotizacion_items enable row level security;
drop policy if exists erp_cotizacion_items_miembros on public.erp_cotizacion_items; create policy erp_cotizacion_items_miembros on public.erp_cotizacion_items for all to authenticated using(exists(select 1 from public.erp_cotizaciones c where c.id=cotizacion_id and public.rest_tiene_acceso(c.empresa_id))) with check(exists(select 1 from public.erp_cotizaciones c where c.id=cotizacion_id and public.rest_tiene_acceso(c.empresa_id)));
drop policy if exists erp_empleados_miembros on public.erp_empleados; create policy erp_empleados_miembros on public.erp_empleados for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
drop policy if exists erp_documentos_miembros on public.erp_documentos; create policy erp_documentos_miembros on public.erp_documentos for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
drop policy if exists erp_tareas_miembros on public.erp_tareas; create policy erp_tareas_miembros on public.erp_tareas for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
drop policy if exists erp_movimientos_contables_miembros on public.erp_movimientos_contables; create policy erp_movimientos_contables_miembros on public.erp_movimientos_contables for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));
drop policy if exists erp_configuracion_miembros on public.erp_configuracion; create policy erp_configuracion_miembros on public.erp_configuracion for all to authenticated using(public.rest_tiene_acceso(empresa_id)) with check(public.rest_tiene_acceso(empresa_id));

create index if not exists erp_clientes_empresa_idx on public.erp_clientes(empresa_id,created_at desc);
create index if not exists erp_proveedores_empresa_idx on public.erp_proveedores(empresa_id,created_at desc);
create index if not exists erp_cotizaciones_empresa_idx on public.erp_cotizaciones(empresa_id,created_at desc);
create index if not exists erp_empleados_empresa_idx on public.erp_empleados(empresa_id,estado);
create index if not exists erp_tareas_empresa_idx on public.erp_tareas(empresa_id,fecha);
create index if not exists erp_contabilidad_empresa_idx on public.erp_movimientos_contables(empresa_id,fecha desc);

-- Administración de usuarios por invitación, sin exponer claves ni usar service_role en el navegador.
create table if not exists public.erp_invitaciones (
 id uuid primary key default gen_random_uuid(), empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
 email text not null, rol text not null check(rol in('administrador','cajero','mozo','cocina')),
 token text not null unique default encode(gen_random_bytes(12),'hex'), estado text not null default 'pendiente' check(estado in('pendiente','usada','revocada')),
 creado_por uuid not null references auth.users(id), created_at timestamptz not null default now(), usada_at timestamptz
);
alter table public.erp_invitaciones enable row level security;

create or replace function public.rest_es_admin(target_empresa uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.rest_miembros where empresa_id=target_empresa and user_id=auth.uid() and activo and rol in('propietario','administrador'));
$$;
grant execute on function public.rest_es_admin(uuid) to authenticated;

drop policy if exists erp_invitaciones_admin on public.erp_invitaciones;
create policy erp_invitaciones_admin on public.erp_invitaciones for all to authenticated using(public.rest_es_admin(empresa_id)) with check(public.rest_es_admin(empresa_id));
drop policy if exists rest_empresas_admin_update on public.rest_empresas;
create policy rest_empresas_admin_update on public.rest_empresas for update to authenticated using(public.rest_es_admin(id)) with check(public.rest_es_admin(id));
drop policy if exists rest_miembros_admin_update on public.rest_miembros;
create policy rest_miembros_admin_update on public.rest_miembros for update to authenticated using(public.rest_es_admin(empresa_id)) with check(public.rest_es_admin(empresa_id));

create or replace function public.erp_crear_invitacion(p_empresa_id uuid,p_email text,p_rol text)
returns public.erp_invitaciones language plpgsql security invoker set search_path=public as $$
declare result public.erp_invitaciones;
begin
 if not public.rest_es_admin(p_empresa_id) then raise exception 'Solo el propietario o administrador puede invitar usuarios'; end if;
 if p_rol not in('administrador','cajero','mozo','cocina') then raise exception 'Rol inválido'; end if;
 insert into public.erp_invitaciones(empresa_id,email,rol,creado_por) values(p_empresa_id,lower(trim(p_email)),p_rol,auth.uid()) returning * into result;
 return result;
end; $$;
grant execute on function public.erp_crear_invitacion(uuid,text,text) to authenticated;

create or replace function public.erp_aceptar_invitacion(p_token text)
returns uuid language plpgsql security definer set search_path=public,auth as $$
declare inv public.erp_invitaciones; current_email text;
begin
 if auth.uid() is null then raise exception 'Debes iniciar sesión'; end if;
 select lower(email) into current_email from auth.users where id=auth.uid();
 select * into inv from public.erp_invitaciones where token=trim(p_token) and estado='pendiente' for update;
 if inv.id is null then raise exception 'Código de invitación inválido o ya utilizado'; end if;
 if lower(inv.email)<>current_email then raise exception 'La invitación pertenece a otro correo'; end if;
 insert into public.rest_miembros(empresa_id,user_id,rol,nombre,activo) values(inv.empresa_id,auth.uid(),inv.rol,split_part(current_email,'@',1),true)
 on conflict(empresa_id,user_id) do update set rol=excluded.rol,activo=true;
 update public.erp_invitaciones set estado='usada',usada_at=now() where id=inv.id;
 return inv.empresa_id;
end; $$;
grant execute on function public.erp_aceptar_invitacion(text) to authenticated;
