-- Huerta ERP: núcleo gastronómico multiempresa
create extension if not exists pgcrypto;

create table if not exists public.rest_empresas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  nombre_comercial text,
  ruc text,
  telefono text,
  direccion text,
  activa boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rest_miembros (
  empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rol text not null default 'administrador' check (rol in ('propietario','administrador','cajero','mozo','cocina')),
  activo boolean not null default true,
  primary key (empresa_id, user_id)
);

create table if not exists public.rest_sucursales (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
  nombre text not null,
  direccion text,
  activa boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rest_productos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
  nombre text not null,
  categoria text not null,
  precio numeric(12,2) not null check (precio >= 0),
  stock numeric(12,3) not null default 0,
  stock_minimo numeric(12,3) not null default 5,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rest_cajas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
  sucursal_id uuid not null references public.rest_sucursales(id) on delete restrict,
  abierta_por uuid not null references auth.users(id),
  cerrada_por uuid references auth.users(id),
  monto_apertura numeric(12,2) not null default 0,
  monto_cierre numeric(12,2),
  estado text not null default 'abierta' check (estado in ('abierta','cerrada')),
  abierta_at timestamptz not null default now(),
  cerrada_at timestamptz
);

create table if not exists public.rest_pedidos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.rest_empresas(id) on delete cascade,
  sucursal_id uuid not null references public.rest_sucursales(id) on delete restrict,
  caja_id uuid references public.rest_cajas(id) on delete restrict,
  numero bigint generated by default as identity,
  tipo_servicio text not null check (tipo_servicio in ('salon','delivery','recojo')),
  mesa text,
  cliente text,
  estado text not null default 'nuevo' check (estado in ('nuevo','preparando','listo','entregado','pagado','anulado')),
  metodo_pago text,
  total numeric(12,2) not null default 0,
  creado_por uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rest_pedido_items (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.rest_pedidos(id) on delete cascade,
  producto_id uuid references public.rest_productos(id) on delete set null,
  nombre text not null,
  cantidad numeric(12,3) not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
  notas text
);

create index if not exists rest_miembros_user_idx on public.rest_miembros(user_id) where activo;
create index if not exists rest_productos_empresa_idx on public.rest_productos(empresa_id, activo);
create index if not exists rest_pedidos_operacion_idx on public.rest_pedidos(empresa_id, sucursal_id, created_at desc);
create index if not exists rest_pedidos_cocina_idx on public.rest_pedidos(empresa_id, estado, created_at) where estado in ('nuevo','preparando','listo');

create or replace function public.rest_tiene_acceso(target_empresa uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.rest_miembros
    where empresa_id = target_empresa and user_id = auth.uid() and activo
  );
$$;

grant execute on function public.rest_tiene_acceso(uuid) to authenticated;

alter table public.rest_empresas enable row level security;
alter table public.rest_miembros enable row level security;
alter table public.rest_sucursales enable row level security;
alter table public.rest_productos enable row level security;
alter table public.rest_cajas enable row level security;
alter table public.rest_pedidos enable row level security;
alter table public.rest_pedido_items enable row level security;

drop policy if exists rest_empresas_miembros on public.rest_empresas;
create policy rest_empresas_miembros on public.rest_empresas for select to authenticated using (public.rest_tiene_acceso(id));
drop policy if exists rest_miembros_propios on public.rest_miembros;
create policy rest_miembros_propios on public.rest_miembros for select to authenticated using (user_id = auth.uid() or public.rest_tiene_acceso(empresa_id));
drop policy if exists rest_sucursales_miembros on public.rest_sucursales;
create policy rest_sucursales_miembros on public.rest_sucursales for all to authenticated using (public.rest_tiene_acceso(empresa_id)) with check (public.rest_tiene_acceso(empresa_id));
drop policy if exists rest_productos_miembros on public.rest_productos;
create policy rest_productos_miembros on public.rest_productos for all to authenticated using (public.rest_tiene_acceso(empresa_id)) with check (public.rest_tiene_acceso(empresa_id));
drop policy if exists rest_cajas_miembros on public.rest_cajas;
create policy rest_cajas_miembros on public.rest_cajas for all to authenticated using (public.rest_tiene_acceso(empresa_id)) with check (public.rest_tiene_acceso(empresa_id));
drop policy if exists rest_pedidos_miembros on public.rest_pedidos;
create policy rest_pedidos_miembros on public.rest_pedidos for all to authenticated using (public.rest_tiene_acceso(empresa_id)) with check (public.rest_tiene_acceso(empresa_id));
drop policy if exists rest_items_miembros on public.rest_pedido_items;
create policy rest_items_miembros on public.rest_pedido_items for all to authenticated
using (exists (select 1 from public.rest_pedidos p where p.id = pedido_id and public.rest_tiene_acceso(p.empresa_id)))
with check (exists (select 1 from public.rest_pedidos p where p.id = pedido_id and public.rest_tiene_acceso(p.empresa_id)));

create or replace function public.rest_crear_empresa_inicial(nombre_empresa text default 'Chicken Huerta')
returns table (empresa_id uuid, sucursal_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  nueva_empresa uuid;
  nueva_sucursal uuid;
begin
  if auth.uid() is null then raise exception 'Sesión requerida'; end if;

  select m.empresa_id, s.id into nueva_empresa, nueva_sucursal
  from public.rest_miembros m
  join public.rest_sucursales s on s.empresa_id = m.empresa_id and s.activa
  where m.user_id = auth.uid() and m.activo
  order by s.created_at
  limit 1;

  if nueva_empresa is null then
    insert into public.rest_empresas (nombre, nombre_comercial)
    values (nombre_empresa, nombre_empresa) returning id into nueva_empresa;
    insert into public.rest_miembros (empresa_id, user_id, rol)
    values (nueva_empresa, auth.uid(), 'propietario');
    insert into public.rest_sucursales (empresa_id, nombre)
    values (nueva_empresa, 'Local principal') returning id into nueva_sucursal;

    insert into public.rest_productos (empresa_id, nombre, categoria, precio, stock) values
      (nueva_empresa, 'Pollo a la brasa entero', 'Pollos', 68, 30),
      (nueva_empresa, '1/2 pollo a la brasa', 'Pollos', 38, 30),
      (nueva_empresa, '1/4 pollo a la brasa', 'Pollos', 20, 50),
      (nueva_empresa, 'Parrilla personal', 'Parrillas', 32, 25),
      (nueva_empresa, 'Mostrito', 'Combos', 22, 40),
      (nueva_empresa, 'Arroz chaufa', 'Platos', 18, 35),
      (nueva_empresa, 'Gaseosa 1 litro', 'Bebidas', 10, 24),
      (nueva_empresa, 'Jarra de chicha morada', 'Bebidas', 12, 20);
  end if;

  return query select nueva_empresa, nueva_sucursal;
end;
$$;

grant execute on function public.rest_crear_empresa_inicial(text) to authenticated;

create or replace function public.rest_crear_pedido(
  p_empresa_id uuid,
  p_sucursal_id uuid,
  p_caja_id uuid,
  p_tipo_servicio text,
  p_mesa text,
  p_cliente text,
  p_items jsonb
)
returns public.rest_pedidos
language plpgsql
security invoker
set search_path = public
as $$
declare
  pedido public.rest_pedidos;
begin
  if not public.rest_tiene_acceso(p_empresa_id) then raise exception 'Sin acceso a la empresa'; end if;
  if jsonb_array_length(p_items) = 0 then raise exception 'El pedido no contiene productos'; end if;

  insert into public.rest_pedidos (empresa_id, sucursal_id, caja_id, tipo_servicio, mesa, cliente, total, creado_por)
  select p_empresa_id, p_sucursal_id, p_caja_id, p_tipo_servicio, nullif(p_mesa, ''), nullif(p_cliente, ''),
    sum((item->>'quantity')::numeric * (item->>'unitPrice')::numeric), auth.uid()
  from jsonb_array_elements(p_items) item
  returning * into pedido;

  insert into public.rest_pedido_items (pedido_id, producto_id, nombre, cantidad, precio_unitario, notas)
  select pedido.id, nullif(item->>'productId','')::uuid, item->>'name', (item->>'quantity')::numeric,
    (item->>'unitPrice')::numeric, nullif(item->>'notes','')
  from jsonb_array_elements(p_items) item;

  return pedido;
end;
$$;

grant execute on function public.rest_crear_pedido(uuid,uuid,uuid,text,text,text,jsonb) to authenticated;

alter publication supabase_realtime add table public.rest_pedidos;
